export const TOOGLE_AUTH = "TOOGLE_AUTH";
export const CHANGE_LOGIN_IS_LOAD = "CHANGE_LOGIN_IS_LOAD";
export const CHANGE_SIGNUP_IS_LOAD = "CHANGE_SIGNUP_IS_LOAD";
export const CHANGE_ORDER_FORM_IS_LOAD = "CHANGE_ORDER_FORM_IS_LOAD";
export const CHANGE_MASTER_LIST_IS_LOAD = "CHANGE_MASTER_LIST_IS_LOAD";
export const CHANGE_SUCCESS_MODAL_DATA = "CHANGE_SUCCESS_MODAL_DATA";
export const CHANGE_TOWNS_FROM_ORDER_FORM_IS_LOAD = "CHANGE_TOWNS_FROM_ORDER_FORM_IS_LOAD";