export const ADD_ORDERS = "ADD_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const CHANGE_ADD_NEW_ORDER_FORM_IS_LOAD =
  "CHANGE_ADD_NEW_ORDER_FORM_IS_LOAD";
export const ADD_CURRNET_ORDER = "ADD_CURRNET_ORDER";
export const CHANGE_ADMIN_ORDER_FORM_IS_LOAD = "CHANGE_ORDER_FORM_IS_LOAD";
export const INIT_USER_ORDERS = "INIT_USER_ORDERS";
export const CHANGE_USER_ORDERS_LIST_IS_LOAD = "CHANGE_USER_ORDERS_LIST_IS_LOAD";
export const CHANGE_CLIENT_ORDER_FORM_IS_LOAD = "CHANGE_CLIENT_ORDER_FORM_IS_LOAD";