export const ADD_NEW_MASTER = "ADD_NEW_MASTER";
export const INIT_MASTERS = "INIT_MASTERS";
export const DELETE_MASTER = "DELETE_MASTER";
export const UPDATE_MASTER = "UPDATE_MASTER";
export const ADD_SUITABLE_MASTERS = "ADD_SUITABLE_MASTERS";
export const CHANGE_ADD_NEW_MASTER_FORM_IS_LOAD =
  "CHANGE_ADD_NEW_MASTER_FORM_IS_LOAD";
export const MSTER_LIST_IS_LOAD = "MSTER_LIST_IS_LOAD";
