export const TOOGLE_AUTH_ADMIN = "TOOGLE_AUTH_ADMIN";
export const TOOGLE_AUTH_CLIENT = "TOOGLE_AUTH_CLIENT";
export const CHANGE_CLIENT_LOGIN_IS_LOAD = "CHANGE_CLIENT_LOGIN_IS_LOAD";
export const CHANGE_SIGNUP_IS_LOAD = "CHANGE_SIGNUP_IS_LOAD";
export const CHANGE_ADMIN_LOGIN_IS_LOAD = "CHANGE_ADMIN_LOGIN_IS_LOAD";
