export const CHNG_CURR_ITEM_FOR_MODAL = "CHNG_CURR_ITEM_FOR_MODAL";
export const CHANGE_SUCCESS_MODAL_DATA_ADMIN =
  "CHANGE_SUCCESS_MODAL_DATA_ADMIN";
export const CHANGE_MODAL_WARNING_DATA_ADMIN =
  "CHANGE_MODAL_WARNING_DATA_ADMIN";
export const CHANGE_LIST_IS_LOAD = "CHANGE_LIST_IS_LOAD";
