export const INIT_NEW_TOWNS = "INIT_NEW_TOWNS";
export const ADD_NEW_TOWN = "ADD_NEW_TOWN";
export const DELETE_TOWN = "DELETE_TOWN";
export const UPDATE_TOWN = "UPDATE_TOWN";
export const CHANGE_ADD_NEW_TOWN_FORM_IS_LOAD =
  "CHANGE_ADD_NEW_TOWN_FORM_IS_LOAD";
